version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - 5000:5000
    restart: always
    extra_hosts:
      - "host.docker.internal:172.23.0.1"

  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:172.23.0.1"