version: '3'

services:
  web:
    build: .
    container_name: webserver
    ports:
      - "5000:5000"
    volumes:
      - ./code:/code
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      - net_projetodados

  db:
    container_name: postgres_prod
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - net_projetodados

networks:
  net_projetodados:
    external:
      name: custom_network